from django.conf.urls import patterns, url
from views import *

#admin.autodiscover()

urlpatterns = patterns('example.views',
  
 url(r'^pro/$', proindex,name="proindex"),
url(r'^$', index,name="index"),
url(r'^404/$',four),
url(r'^500/$',five),
url(r'^badges_labels/$',badges_labels),
url(r'^basic_gallery/$',basic_gallery),
url(r'^buttons/$',buttons),
url(r'^calendar/$',calendar),
url(r'^carousel/$',carousel),
url(r'^chat_view/$',chat_view),
url(r'^code_editor/$',code_editor),
url(r'^contacts/$',contacts),
url(r'^css_animation/$',css_animation),
url(r'^draggable_panels/$',draggable_panels),
url(r'^empty_page/$',empty_page),
url(r'^faq/$',faq),
url(r'^file_manager/$',file_manager),
url(r'^form_advanced/$',form_advanced),
url(r'^form_avatar/$',form_avatar),
url(r'^form_basic/$',form_basic),
url(r'^form_builder/$',form_builder),
url(r'^form_editors/$',form_editors),
url(r'^form_file_upload/$',form_file_upload),
url(r'^form_markdown/$',form_markdown),
url(r'^form_simditor/$',form_simditor),
url(r'^form_validate/$',form_validate),
url(r'^form_webuploader/$',form_webuploader),
url(r'^form_wizard/$',form_wizard),
url(r'^forum_main/$',forum_main),
url(r'^graph_echarts/$',graph_echarts),
url(r'^graph_flot/$',graph_flot),
url(r'^graph_morris/$',graph_morris),
url(r'^graph_peity/$',graph_peity),
url(r'^graph_rickshaw/$',graph_rickshaw),
url(r'^graph_sparkline/$',graph_sparkline),
url(r'^grid_options/$',grid_options),
url(r'^iconfont/$',iconfont),
url(r'^icons/$',icons),
url(r'^index/$',index),
url(r'^index_1/$',index_1),
url(r'^index_2/$',index_2),
url(r'^index_3/$',index_3),
url(r'^index_4/$',index_4),
url(r'^invoice/$',invoice),
url(r'^invoice_print/$',invoice_print),
url(r'^layer/$',layer),
url(r'^layerdate/$',layerdate),
url(r'^layouts/$',layouts),
url(r'^lockscreen/$',lockscreen),
url(r'^login/$',login),
url(r'^mailbox/$',mailbox),
url(r'^mail_compose/$',mail_compose),
url(r'^mail_detail/$',mail_detail),
url(r'^modal_window/$',modal_window),
url(r'^nestable_list/$',nestable_list),
url(r'^notifications/$',notifications),
url(r'^pin_board/$',pin_board),
url(r'^profile/$',profile),
url(r'^projects/$',projects),
url(r'^project_detail/$',project_detail),
url(r'^register/$',register),
url(r'^search_results/$',search_results),
url(r'^table_basic/$',table_basic),
url(r'^table_data_tables/$',table_data_tables),
url(r'^table_jqgrid/$',table_jqgrid),
url(r'^tabs_panels/$',tabs_panels),
url(r'^timeline/$',timeline),
url(r'^timeline_v2/$',timeline_v2),
url(r'^toastr_notifications/$',toastr_notifications),
url(r'^tree_view/$',tree_view),
url(r'^tree_view_v2/$',tree_view_v2),
url(r'^typography/$',typography),
url(r'^validation/$',validation),
url(r'^webim/$',webim),
url(r'^widgets/$',widgets),
)